language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cheonu/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true cheonu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: "docker-react"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-ca-central-1-311038906131"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY